### ISSUE TITLE
Roadmap for version 4

### ISSUE THREAD

**Issue by sodatea** [vuejs/vue-cli#3649]
It's time for a major version bump.
This will be a relatively small release but will include a number of necessary breaking changes.

### Dependency Updates

- [x] webpack-chain v5 (#3913) [CHANGELOG](https://github.com/neutrinojs/webpack-chain/blob/master/CHANGELOG.md)
- [x] css-loader v2 (#3866) [CHANGELOG](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md)
- [x] copy-webpack-plugin v5 [CHANGELOG](https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md) (a very subtle change, unless you've touched its options in config there won't be any affect)
- [x] Nightwatch v1 (#3388) [MIGRATION GUIDE](https://github.com/nightwatchjs/nightwatch/wiki/Migrating-to-Nightwatch-1.0)
- [x] Use ESLint v5 by default (#3775) (projects scaffolded with Vue CLI 3.1+ are already using it, for those scaffolded by 3.0.x, here's the [migration guide for eslint](https://eslint.org/docs/5.0.0/user-guide/migrating-to-5.0.0) and [release note of eslint-plugin-vue v5](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v5.0.0))
- [x] Jest v24 (#3870) [RELEASE NOTE](https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly)
- [x] workbox v4 (#3915) [RELEASE NOTE](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0) and [MIGRATION GUIDE](https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3)
- [x] core-js 3 ([#3912](https://github.com/vuejs/vue-cli/pull/3912)) (It's an internal change of `@vue/babel-preset/app`, for now we use core-js 2 by default, [babel 7.4.0 supports core-js 3](https://github.com/babel/babel/pull/7646), once we upgraded core-js, some **undocumented** public APIs may change)

### Changed Behavior

- [x] `vue-template-loader`: `preserveWhitespace: false` -> `whitespace: 'condense'` #3853
- [x] use `NODE_ENV=production` by default if not specified when running `vue-cli-service build` #3859
- [x] `plugin-pwa`: `manifest.json` should be generated during the build process rather than scaffolding #2981

### New Features

Most proposed new features other than plugin APIs can also be landed in v3.x so they are not listed here.

- [x] Plugin API: Allow plugins to provide a minimum vue-cli version #3861
- [x] `vue upgrade` overhaul, allowing running codemods from plugins
- [ ] Plugin ordering #1754, #1938

### Removed

- [ ] Drop Node.js v9 support (in documentation, no need to touch the code)
- [x] remove support for `vue-cli-service e2e` command (already deprecated since 3.0 rc) (#3774)

## Needs Discussion

- [ ] <del>Drop unit mocha in favor of Jest only
  - Mostly because [mocha-webpack](https://github.com/zinserjan/mocha-webpack/) is unmaintained and unlikely to work with webpack 5
  - Need good migration strategy for existing users</del>
- [x] Use mochapack instead of mocha-webpack
- [x] Upgrade to mocha v6

## How Can I Help?

Please let us know your thoughts and if we missed anything.
We'll be more than happy to explain our rationale around these decisions if there's any further questions.

If there's anything you (and the community) feel strongly about but is not found on this list, please make an effort to send a PR!
We'll be more than happy to accept contributions.

**Comment by ZainW** [comment]
any elaboration/details on what the breaking changes have to do with? is it all the dependencies you listed ?

my guess is webpack v5 being the biggest breaking change (possibly)but thats just me guessing

**Comment by edimitchel** [comment]
Mocha is much faster than Jest. Keep it.

**Comment by NeiPCs** [comment]
Yep, since we know what breaking changes will apply, we can work on documentation of migration from X to Y version.

**Comment by LinusBorg** [comment]
> Mocha is much faster than Jest. Keep it.

We would, if someone can point explain to assure us mocha-webpack will continue to work with webpack 5 if it's unmaintained.

Otherwise we just keep a feature alive that is destined to die soon anyway.

**Comment by salvadordiaz** [comment]
There is a fork of mocha-webpack that works with webpack 4 and mocha 4, 5 and 6: 
https://github.com/sysgears/mochapack

I really hope that we can avoid having to migrate our test suite from mocha to jest.

**Comment by Garito** [comment]
My 5 cents: the simpler the better

**Comment by LinusBorg** [comment]
@salvadordiaz That looks promising, assuming the author is up to upgrade it to webpack 5 compatibility when that time arrives.

**Comment by geedew** [comment]
Is there a discussion ticket for the Codemods work?

**Comment by LinusBorg** [comment]
Nope. Also, we should probably do a real RFC for his as the vue-cli repo is one of the repos we included for the official RFC process in https://github.com/vuejs/rfcs#when-to-follow-this-process

**Comment by yannick-milanetto** [comment]
Is there any plans to support server-side rendering in core, without having to go with a 3rd party plugin ?

**Comment by vlasenko** [comment]
@LinusBorg Hi Linus, I'm the maintainer of `mochapack`. Is Webpack 5 support is the only thing you need to continue using mocha unit tests and `mocha-webpack`, or have you made a decision to drop mocha tests in favor of `jest` already?

**Comment by LinusBorg** [comment]
@vlasenko Hi 😁 

We haven't made that decision, that's what this issue is meant to discuss. 

We don't want to "get rid" of mocha. Until someone mentioned your fork, we just didn't see any future for it since mocha webpack was unmaintained. 

So if you ate panning to keep on working on mochapack and make it work with webpack 5, my opinion would be to keep it 🙂

**Comment by vlasenko** [comment]
@LinusBorg Great! Yes, I plan to keep on working on `mochapack` and add Wepback 5 support to it. I will notify you here, when Webpack 5 support will be ready in `mochapack`.

**Comment by cngu** [comment]
@LinusBorg Hi! Based on the discussion here https://github.com/vuejs/vue-cli/issues/947#issuecomment-370796856, has an alternative for inject-loader been investigated yet?  

If not, Jest has some complimentary features to help replace inject-loader that you may want to consider when comparing it with Mocha.

**Comment by pksunkara** [comment]
Thanks for creating this @sodatea and @LinusBorg. It's good to see the development of this repo is more transparent now. I can work on the new features (some of it already done) since I was the one who was requesting them mostly. We can discuss more if you guys want. I will be available in the Vue Discord.

**Comment by pksunkara** [comment]
@geedew 

> Is there a discussion ticket for the Codemods work?

There is some discussion about the scenarios that need to be handled in https://github.com/vuejs/vue-cli/issues/1507 when the original work for vue-upgrade has been done.

For an example issue that rose up because vue-upgrade is not properly done is in storybook plugin linked [here](https://github.com/storybooks/vue-cli-plugin-storybook/issues/54)

**Comment by KyLeoHC** [comment]
Think about replacing tslint with typescript-eslint.And replace ts-loader with babel7.

**Comment by LinusBorg** [comment]
> replacing tslint with typescript-eslint

We will do that once typescript-eslint has the announced feature parity with tslint.

> And replace ts-loader with babel7.

Since babel's typescript implementation comes with some significant limitations we probably won't do that.

**Comment by andreiTn** [comment]
TSLint doesn't detect HTML errors inside <template>.
Steps to reproduce:
1. Create a new Vue project with Typescript and TSLint.
2. Create an error inside HTML in a `.vue` file. For example, remove an angle bracket `<` from a tag.
3. Run `yarn lint`

Output: No lint errors found!

ESLin detects this, however, I don't know if I should use ESLint with Typescript or ESLint together with TSLint. Is this something that you could look into for the next version?

**Comment by IndexXuan** [comment]
@andreiTn you should use eslint with ts，since it support ts and will support by the core ts team in the futher. tslint is deprecated！

**Comment by andreiTn** [comment]
Thanks @IndexXuan

**Comment by 752** [comment]
update html-webpack-plugin to 4.x ?
[https://github.com/jantimon/html-webpack-plugin/issues/878](url)
[https://github.com/jantimon/html-webpack-plugin/issues/1069](url)

**Comment by LinusBorg** [comment]
Sure, once it's out of beta (currently: `4.0.0-beta.5`)

**Comment by alvarosaburido** [comment]
Have you thought about adding commands for scaffolding, to easy create views, components, stores? Similar to https://github.com/hjeti/vue-generator. You can also create a directory with your own templates (with your code conventions) inside of your project.

**Comment by TerenceZ** [comment]
Think about repace `ts-loader` with  `@babel/preset-typescript`.

**Comment by sodatea** [comment]
@TerenceZ babel's parser does not support all of typescript syntax so no.

**Comment by pksunkara** [comment]
One more task, update less-loader to v5

**Comment by pksunkara** [comment]
@sodatea @LinusBorg IMO we should also resolve #2335 before v4

**Comment by moranje** [comment]
Hope you are aware of:

https://eslint.org/docs/6.0.0/user-guide/migrating-to-6.0.0

**Comment by ashleynolan** [comment]
Are there any plans to add ES6 module output to the `library` build mode in a future version of vue-cli?

**Comment by sodatea** [comment]
@ashleynolan pending https://github.com/webpack/webpack/issues/2933

**Comment by ffxsam** [comment]
Another vote to get rid of the TSLint option in vue-cli, as it's being deprecated. I've replaced it with the new TypeScript ESLint plugin, and does just fine validating my code.

[Full ruleset here.](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules)

**Comment by sodatea** [comment]
@ffxsam PR submitted https://github.com/vuejs/vue-cli/pull/4289

**Comment by bodograumann** [comment]
I see the “vue upgrade” item is marked done. There are some open in points in https://github.com/vuejs/vue-cli/pull/4090 though. Most importantly there is no documentation for the `MigrationAPI`.

Secondly, the linked tickets for “plugin ordering” are resolved by https://github.com/vuejs/vue-cli/pull/2337. Is there anything else planned for 4.0?

Finally, any predictions on a release date?

**Comment by sodatea** [comment]
For the `vue upgrade` command:
It still needs refinement, but is usable. So it won't block v4 stable release, we can do the refinement in later feature releases.

The `MigratorAPI`:
It's the same as `GeneratorAPI` with an additional `fromVersion(range)` method. I'nm working on the documentation.

Plugin Ordering:
Not fully solved, but the most common concerns have been addressed and I believe most use cases can be solved or worked around with the latest API.
No major new features planned as of now.

Release date:
v4 is now in beta, meaning it's mostly usable with maybe a few glitches. Feedbacks are welcome.

The next step is to fixing noticable bugs and refining the documentation.
Actually I'm working on a blog post to introduce its major changes but haven't got the time to finish it.
I'd like to complete the beta and then rc phase in the coming weeks, but this is not set in stone, in case any major issues encountered during the test.

**Comment by falstack** [comment]
### Multiple Component Lib support.

#### src dir
```
// src
-- componentA
  |-- index.js
  |-- a.vue
-- componentB
  |-- index.js
  |-- b.vue
```

#### build script
```
"build": "vue-cli-service build --target lib --name myLib 'src/**/index.js'"
```

#### output dir
```
// dist
myLib.xxx.js
myLib.min.css
componentA
  |-- index.js
  |-- style.css
componentB
  |-- index.js
  |-- style.css
```

**Comment by bodograumann** [comment]
`typescript-eslint` version 2.0.0 was [just released](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0)!
Lots of changes; probably requires modifying `@vue/eslint-config-typescript`. Oh, just seeing that that has been moved to [its own repository](https://github.com/vuejs/eslint-config-typescript). So not sure how you want to handle this.

**Comment by pksunkara** [comment]
eslint-config-airbnb 14.0.0 released to be in line with eslint 6

**Comment by sodatea** [comment]
ESLint config versions are managed separately from `@vue/cli-plugin-eslint`.
If they have new versions, the default config versions used for generating new projects will be bumped in a minor release of the plugin.

I'd also like to implement an upgrade hook in the plugin, to prompt the user to optionally update the config version and its peer dependencies. This feature may or may not land in 4.0 because it seems not that urgent.

**Comment by bodograumann** [comment]
I would love to see that, @sodatea. I often have the problem that `npm update` installs a new version of `typescript` but `@typescript-eslint/*` are not updated. That leads to the usual “typescript version not supported” warning and to linting issues. Of course I can fix it with a deep update, but a more care-free solutions would be much appreciated.

**Comment by linden5** [comment]
How about supporting running vue-cli-service programatically by passing in user options?

**Comment by LinusBorg** [comment]
Not sure what exactly you mean by that ...?

**Comment by georgyfarniev** [comment]
Why vue-cli uses nightwatch instead of puppeteer? For running against multiple browsers?

**Comment by LinusBorg** [comment]
Exactly.

If you want to run against chrome only, we offer Cypress.

**Comment by CommanderXL** [comment]
Is there any possible to add a hook for developers to modify the README.md?

In most situations, we use vue-cli to create some projects with default README.md generated by the [readme.md utility function](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/generateReadme.js).So we want to generate the README.md file with different content after a project created by vue-cli.

**Comment by bodograumann** [comment]
Cf. https://github.com/vuejs/vue-cli/issues/3547 @CommanderXL

**Comment by CommanderXL** [comment]
@bodograumann Well, I have seen that issue.So will it come to the vue-cli of v4? Or need us to do some pull request to accomplish this function?

**Comment by LinusBorg** [comment]
it's now marked as "contribution welcome" so we would be happy to see a PR for this.

**Comment by georgyfarniev** [comment]
Hello folks, I see that vue-next uses rollup for build, so is there any plan to support it as alternative to webpack in vue-cli?

**Comment by LinusBorg** [comment]
No.

**Comment by georgyfarniev** [comment]
> No. Supporting two build tools will increase complexity too much.

Agreed, thanks. So it will be used only for vue due to its simplicity

**Comment by sodatea** [comment]
Released 🎉
The release note: https://github.com/vuejs/vue-cli/releases/tag/v4.0.0
The migration guide: https://cli.vuejs.org/migrating-from-v3/
